import { X, Clock, CheckCircle2, Circle, Printer, FileText, ScanBarcode } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/dateUtils";

export type HistoryType = 'MAIN' | 'FILE' | 'PLATE';

export interface HistoryEntry {
  status: string;
  timestamp: string;
  updatedBy: string;
  duration?: string;
  type?: HistoryType;
  note?: string;
}

interface HistoryModalProps {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  carModel: string;
  chassisNumber: string;
  history: HistoryEntry[];
  fullHistory: HistoryEntry[];
}

export const HistoryModal = ({
  isOpen,
  onClose,
  title = "Status History",
  carModel,
  chassisNumber,
  history,
  fullHistory = []
}: HistoryModalProps) => {
  if (!isOpen) return null;

  // Sort history reverse chronological (newest first) for display
  const sortedHistory = [...history].reverse();

  const handlePrint = (filterType: 'ALL' | 'FILE' | 'PLATE') => {
    // 1. Filter Data (Use fullHistory if available, otherwise fallback to history)
    const sourceData = fullHistory.length > 0 ? fullHistory : history;
    const dataToPrint = sourceData.filter(h =>
      filterType === 'ALL' ? true :
        filterType === 'FILE' ? h.type === 'FILE' :
          filterType === 'PLATE' ? h.type === 'PLATE' : false
    ).reverse(); // Newest first

    if (dataToPrint.length === 0) return alert("No history found for this category.");

    // 2. Generate HTML
    const printWindow = window.open('', '', 'width=800,height=600');
    if (!printWindow) return;

    const titleText = filterType === 'ALL' ? "Complete Vehicle History" :
      filterType === 'FILE' ? "Document Processing History" :
        "Number Plate History";

    const content = `
      <html>
        <head>
          <title>Print History - ${chassisNumber}</title>
          <style>
            body { font-family: sans-serif; padding: 20px; }
            .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #eee; padding-bottom: 15px; }
            .meta { margin-bottom: 20px; font-size: 14px; color: #555; }
            table { w-full; width: 100%; border-collapse: collapse; font-size: 12px; }
            th { text-align: left; background: #f8f9fa; padding: 8px; border-bottom: 1px solid #ddd; }
            td { padding: 8px; border-bottom: 1px solid #eee; }
            .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; border: 1px solid #ccc; font-size: 10px; }
            .footer { margin-top: 30px; font-size: 10px; color: #999; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2 style="margin:0;">Zohaib Motors Tracking System</h2>
            <p style="margin:5px 0 0;">${titleText}</p>
          </div>
          
          <div class="meta">
            <strong>Vehicle:</strong> ${carModel}<br/>
            <strong>Chassis:</strong> ${chassisNumber}<br/>
            <strong>Date Printed:</strong> ${new Date().toLocaleString()}
          </div>

          <table>
            <thead>
              <tr>
                <th style="width: 140px;">Timestamp</th>
                <th>Status / Action</th>
                <th>Stage Duration</th>
                <th>Category</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              ${dataToPrint.map(entry => `
                <tr>
                  <td>${new Date(entry.timestamp).toLocaleString()}</td>
                  <td><b>${entry.status}</b></td>
                  <td>${entry.duration || '-'}</td>
                  <td><span class="badge">${entry.type || 'MAIN'}</span></td>
                  <td style="color: #666; font-style: italic;">${entry.note || '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            Generated by Zohaib Motors Tracking System
          </div>
        </body>
      </html>
    `;

    // 3. Write and Print
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm animate-in fade-in duration-200">
      <Card className="w-full max-w-lg max-h-[85vh] flex flex-col shadow-xl bg-card dark:bg-slate-900">
        <div className="flex items-center justify-between p-4 border-b border-border">
          <div>
            <h3 className="font-semibold text-lg">{title}</h3>
            <p className="text-xs text-muted-foreground">{carModel} • <span className="font-mono">{chassisNumber}</span></p>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} className="h-8 w-8">
            <X size={18} />
          </Button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          {sortedHistory.length === 0 ? (
            <div className="text-center text-muted-foreground py-8 text-sm">No history recorded for this section.</div>
          ) : (
            <div className="relative pl-4 border-l-2 border-border space-y-8">
              {sortedHistory.map((entry, index) => {
                const isLatest = index === 0;
                return (
                  <div key={index} className="relative">
                    {/* Timeline Dot */}
                    <div className={`absolute -left-[21px] top-1 h-4 w-4 rounded-full border-2 flex items-center justify-center bg-card ${isLatest ? "border-blue-500 text-blue-500" : "border-slate-300 text-muted-foreground"
                      }`}>
                      {isLatest ? <CheckCircle2 size={10} fill="currentColor" className="text-white" /> : <Circle size={8} className="fill-slate-100" />}
                    </div>

                    <div className="flex flex-col space-y-1">
                      <div className="flex items-center justify-between gap-2">
                        <Badge variant={isLatest ? "default" : "outline"} className="w-fit truncate max-w-[200px]">
                          {entry.status}
                        </Badge>
                        <span className="text-[10px] text-muted-foreground whitespace-nowrap">
                          {formatDate(entry.timestamp)}
                        </span>
                      </div>

                      {/* Duration Info */}
                      {entry.duration && entry.duration !== "N/A" && (
                        <div className="flex items-center text-[10px] text-muted-foreground mt-1 bg-muted p-1.5 rounded w-fit">
                          <Clock size={10} className="mr-1.5" />
                          <span>In stage: <span className="font-semibold text-foreground">{entry.duration}</span></span>
                        </div>
                      )}

                      {entry.note && (
                        <p className="text-xs text-muted-foreground italic mt-1">"{entry.note}"</p>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        <div className="p-4 border-t border-border bg-muted/50 rounded-b-xl flex flex-col gap-3">
          <div className="flex gap-2">
            <Button variant="outline" size="sm" className="flex-1 text-xs" onClick={() => handlePrint('ALL')}>
              <Printer size={12} className="mr-1" /> All
            </Button>
            <Button variant="outline" size="sm" className="flex-1 text-xs" onClick={() => handlePrint('FILE')}>
              <FileText size={12} className="mr-1" /> Docs
            </Button>
            <Button variant="outline" size="sm" className="flex-1 text-xs" onClick={() => handlePrint('PLATE')}>
              <ScanBarcode size={12} className="mr-1" /> Plate
            </Button>
          </div>
          <Button className="w-full bg-slate-900" onClick={onClose}>Close</Button>
        </div>
      </Card>
    </div>
  );
};